blank_issues_enabled: false
contact_links:
  - name: ioBroker Community
    url: https://forum.iobroker.net/topic/82345/test-adapter-weatherflow-tempest-api
    about: Please ask and answer questions here.
